# Generated by Django 2.1 on 2019-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190423_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gened_subject',
            name='prerequisite',
            field=models.IntegerField(default=1),
        ),
    ]
