# Generated by Django 2.1 on 2019-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190423_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_major',
            name='course_gened',
        ),
        migrations.AddField(
            model_name='gened_subject',
            name='credit',
            field=models.IntegerField(default=1),
        ),
    ]
