# Generated by Django 2.1 on 2019-04-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190423_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_major',
            name='course_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polls.Course_Year'),
            preserve_default=False,
        ),
    ]
