# Generated by Django 2.1 on 2019-04-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_course_major_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_major',
            name='year',
        ),
    ]
