# Generated by Django 2.1 on 2019-05-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_user_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_require',
            name='detail',
        ),
        migrations.AddField(
            model_name='subject_require',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.GenEd_Subject'),
        ),
        migrations.AddField(
            model_name='subject_require',
            name='subject_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polls.Courese_GenEd'),
            preserve_default=False,
        ),
    ]
