# Generated by Django 2.1 on 2019-05-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190502_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='report_why',
            field=models.TextField(null=True),
        ),
    ]
