# Generated by Django 2.1 on 2019-05-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190503_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='report_why',
        ),
    ]
