# Generated by Django 2.1 on 2019-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_review_report_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='annonymous',
            field=models.BooleanField(default=False),
        ),
    ]
