# Generated by Django 2.1 on 2019-05-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190503_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='human_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate_point',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.GenEd_Subject'),
        ),
        migrations.AlterField(
            model_name='review',
            name='verify',
            field=models.BooleanField(null=True),
        ),
    ]
