# Generated by Django 2.1 on 2019-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_comment_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
