# Generated by Django 2.1 on 2019-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190504_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
