# Generated by Django 2.1 on 2019-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190504_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='study_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
