# Generated by Django 2.1 on 2019-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_review_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='teacher_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
