# Generated by Django 2.1 on 2019-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_review_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='annonymous',
            field=models.BooleanField(default=False),
        ),
    ]
