# Generated by Django 2.1 on 2019-05-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_comment_annonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='report',
        ),
        migrations.RemoveField(
            model_name='review',
            name='report_detail',
        ),
        migrations.AddField(
            model_name='reportreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Review'),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
