# Generated by Django 2.1 on 2019-05-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20190504_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportreview',
            old_name='detail',
            new_name='detail_review',
        ),
    ]
