# Generated by Django 2.1 on 2019-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20190504_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
