# Generated by Django 2.1 on 2019-05-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20190504_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
