# Generated by Django 2.1 on 2019-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20190505_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='teacher_name',
            field=models.CharField(max_length=1000),
        ),
    ]
