# Generated by Django 2.1 on 2019-04-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gened_subject',
            old_name='name',
            new_name='name_th',
        ),
    ]
