# Generated by Django 2.1 on 2019-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_gened_subject_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gened_subject',
            name='prerequisite',
            field=models.IntegerField(default=0),
        ),
    ]
